package com.inz.about.dao;

import com.inz.about.model.DiaryInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DiaryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_info
     *
     * @mbggenerated
     */
    int insert(DiaryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_info
     *
     * @mbggenerated
     */
    int insertSelective(DiaryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_info
     *
     * @mbggenerated
     */
    DiaryInfo selectByPrimaryKey(String diaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DiaryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DiaryInfo record);

    /**
     * 通过用户ID 查询日志信息
     *
     * @param userId   用户ID
     * @param start    开始页数
     * @param pageSize 页面可见数量
     * @return 日志
     */
    List<DiaryInfo> findByUserId(String userId, int start, int pageSize);

    /**
     * 获取全部日志信息
     *
     * @param start    开始页数
     * @param pageSize 页面可见数量
     * @return 日志
     */
    List<DiaryInfo> findAll(int start, int pageSize);
}