package com.inz.about.dao;

import com.inz.about.model.DiaryFile;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DiaryFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String maperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int insert(DiaryFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int insertSelective(DiaryFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    DiaryFile selectByPrimaryKey(String maperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DiaryFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DiaryFile record);

    /**
     * 通过文件Id 获取
     *
     * @param fileId 文件ID
     * @return 日志文件
     */
    List<DiaryFile> findByFileId(String fileId);

    /**
     * 通过日志Id获取
     *
     * @param diaryId 日志ID
     * @return 日志文件
     */
    List<DiaryFile> findByDiaryId(String diaryId);
}