package com.inz.about.dao;

import com.inz.about.model.DiaryPicture;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DiaryPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int insert(DiaryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int insertSelective(DiaryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    DiaryPicture selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DiaryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DiaryPicture record);

    /**
     * 通过日志ID 查询
     *
     * @param diaryId  日志ID
     * @param start    开始项
     * @param pageSize 页面数
     * @return 日志图片
     */
    List<DiaryPicture> findByDiaryId(@Param("diaryId") String diaryId, @Param("start") int start, @Param("pageSize") int pageSize);
}