package com.inz.about.dao;

import com.inz.about.model.DiaryFile;

public interface DiaryFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String maperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int insert(DiaryFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int insertSelective(DiaryFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    DiaryFile selectByPrimaryKey(String maperId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DiaryFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DiaryFile record);
}