package com.inz.about.dao;

import com.inz.about.model.DiaryPicture;

public interface DiaryPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int insert(DiaryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int insertSelective(DiaryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    DiaryPicture selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DiaryPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DiaryPicture record);
}