package com.inz.about.dao;

import com.inz.about.model.FileInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface FileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated
     */
    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated
     */
    int insertSelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated
     */
    FileInfo selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileInfo record);

    /**
     * 通过文件类型查询
     *
     * @param fileType 文件类型
     * @param start    开始位置
     * @param pageSize 页面大小
     * @return 文件集合
     */
    List<FileInfo> findByFileType(@Param("fileType") String fileType, @Param("start") int start, @Param("pageSize") int pageSize);
}