package com.inz.about.dao;

import com.inz.about.model.PictureInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PictureInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_info
     *
     * @mbggenerated
     */
    int insert(PictureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_info
     *
     * @mbggenerated
     */
    int insertSelective(PictureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_info
     *
     * @mbggenerated
     */
    PictureInfo selectByPrimaryKey(String pictureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PictureInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PictureInfo record);
}