package com.inz.about.dao;

import com.inz.about.model.StaticZipCode;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StaticZipCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String zipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int insert(StaticZipCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int insertSelective(StaticZipCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    StaticZipCode selectByPrimaryKey(String zipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticZipCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticZipCode record);

    /**
     * 查询所有
     *
     * @return 邮编
     */
    List<StaticZipCode> findAll();

    /**
     * 通过 区/县Id 获取
     *
     * @param regionId 区/县 Id
     * @return 邮编
     */
    List<StaticZipCode> findByRegionId(String regionId);
}