package com.inz.about.dao;

import com.inz.about.model.StaticCity;

public interface StaticCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String staticCityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int insert(StaticCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int insertSelective(StaticCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    StaticCity selectByPrimaryKey(String staticCityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticCity record);
}