package com.inz.about.dao;

import com.inz.about.model.StaticRegion;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StaticRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String staticRegionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int insert(StaticRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int insertSelective(StaticRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    StaticRegion selectByPrimaryKey(String staticRegionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticRegion record);

    /**
     * 查询全部
     *
     * @return 区/县
     */
    List<StaticRegion> findAll();

    /**
     * 通过地级市ID 查询
     *
     * @param cityId 地级市ID
     * @return 区/县
     */
    List<StaticRegion> findByCityId(String cityId);
}