package com.inz.about.dao;

import com.inz.about.model.StaticProvince;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StaticProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_province
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String staticProvinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_province
     *
     * @mbggenerated
     */
    int insert(StaticProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_province
     *
     * @mbggenerated
     */
    int insertSelective(StaticProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_province
     *
     * @mbggenerated
     */
    StaticProvince selectByPrimaryKey(String staticProvinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticProvince record);
}