package com.inz.about.dao;

import com.inz.about.model.StaticCity;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StaticCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String staticCityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int insert(StaticCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int insertSelective(StaticCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    StaticCity selectByPrimaryKey(String staticCityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticCity record);

    /**
     * 查询所有
     *
     * @return 地级市
     */
    List<StaticCity> findAll();

    /**
     * 通过省ID 查询
     *
     * @param provinceId 省ID
     * @return 地级市
     */
    List<StaticCity> findByProvinceId(String provinceId);

    /**
     * 查询热门城市
     *
     * @return 地级市
     */
    List<StaticCity> findByHot();
}