package com.inz.about.dao;

import com.inz.about.model.StaticZipCode;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface StaticZipCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String zipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int insert(StaticZipCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int insertSelective(StaticZipCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    StaticZipCode selectByPrimaryKey(String zipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticZipCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_zipcode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticZipCode record);
}