package com.inz.about.dao;

import com.inz.about.model.StaticRegion;

public interface StaticRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String staticRegionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int insert(StaticRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int insertSelective(StaticRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    StaticRegion selectByPrimaryKey(String staticRegionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StaticRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table static_region
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticRegion record);
}