package com.inz.about.dao;

import com.inz.about.model.TempEmail;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TempEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_email
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String emailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_email
     *
     * @mbggenerated
     */
    int insert(TempEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_email
     *
     * @mbggenerated
     */
    int insertSelective(TempEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_email
     *
     * @mbggenerated
     */
    TempEmail selectByPrimaryKey(String emailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TempEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_email
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TempEmail record);
}