package com.inz.about.model;

import java.util.Date;

public class DiaryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.diary_id
     *
     * @mbggenerated
     */
    private String diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.diary_user_id
     *
     * @mbggenerated
     */
    private String diaryUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.diary_content
     *
     * @mbggenerated
     */
    private String diaryContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.diary_have_image
     *
     * @mbggenerated
     */
    private String diaryHaveImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.diary_weather
     *
     * @mbggenerated
     */
    private String diaryWeather;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.diary_address
     *
     * @mbggenerated
     */
    private String diaryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.diary_order
     *
     * @mbggenerated
     */
    private String diaryOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.diary_is_more_one
     *
     * @mbggenerated
     */
    private String diaryIsMoreOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_info.update_datatime
     *
     * @mbggenerated
     */
    private Date updateDatatime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.diary_id
     *
     * @return the value of diary_info.diary_id
     *
     * @mbggenerated
     */
    public String getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.diary_id
     *
     * @param diaryId the value for diary_info.diary_id
     *
     * @mbggenerated
     */
    public void setDiaryId(String diaryId) {
        this.diaryId = diaryId == null ? null : diaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.diary_user_id
     *
     * @return the value of diary_info.diary_user_id
     *
     * @mbggenerated
     */
    public String getDiaryUserId() {
        return diaryUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.diary_user_id
     *
     * @param diaryUserId the value for diary_info.diary_user_id
     *
     * @mbggenerated
     */
    public void setDiaryUserId(String diaryUserId) {
        this.diaryUserId = diaryUserId == null ? null : diaryUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.diary_content
     *
     * @return the value of diary_info.diary_content
     *
     * @mbggenerated
     */
    public String getDiaryContent() {
        return diaryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.diary_content
     *
     * @param diaryContent the value for diary_info.diary_content
     *
     * @mbggenerated
     */
    public void setDiaryContent(String diaryContent) {
        this.diaryContent = diaryContent == null ? null : diaryContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.diary_have_image
     *
     * @return the value of diary_info.diary_have_image
     *
     * @mbggenerated
     */
    public String getDiaryHaveImage() {
        return diaryHaveImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.diary_have_image
     *
     * @param diaryHaveImage the value for diary_info.diary_have_image
     *
     * @mbggenerated
     */
    public void setDiaryHaveImage(String diaryHaveImage) {
        this.diaryHaveImage = diaryHaveImage == null ? null : diaryHaveImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.diary_weather
     *
     * @return the value of diary_info.diary_weather
     *
     * @mbggenerated
     */
    public String getDiaryWeather() {
        return diaryWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.diary_weather
     *
     * @param diaryWeather the value for diary_info.diary_weather
     *
     * @mbggenerated
     */
    public void setDiaryWeather(String diaryWeather) {
        this.diaryWeather = diaryWeather == null ? null : diaryWeather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.diary_address
     *
     * @return the value of diary_info.diary_address
     *
     * @mbggenerated
     */
    public String getDiaryAddress() {
        return diaryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.diary_address
     *
     * @param diaryAddress the value for diary_info.diary_address
     *
     * @mbggenerated
     */
    public void setDiaryAddress(String diaryAddress) {
        this.diaryAddress = diaryAddress == null ? null : diaryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.diary_order
     *
     * @return the value of diary_info.diary_order
     *
     * @mbggenerated
     */
    public String getDiaryOrder() {
        return diaryOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.diary_order
     *
     * @param diaryOrder the value for diary_info.diary_order
     *
     * @mbggenerated
     */
    public void setDiaryOrder(String diaryOrder) {
        this.diaryOrder = diaryOrder == null ? null : diaryOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.diary_is_more_one
     *
     * @return the value of diary_info.diary_is_more_one
     *
     * @mbggenerated
     */
    public String getDiaryIsMoreOne() {
        return diaryIsMoreOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.diary_is_more_one
     *
     * @param diaryIsMoreOne the value for diary_info.diary_is_more_one
     *
     * @mbggenerated
     */
    public void setDiaryIsMoreOne(String diaryIsMoreOne) {
        this.diaryIsMoreOne = diaryIsMoreOne == null ? null : diaryIsMoreOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.create_datetime
     *
     * @return the value of diary_info.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.create_datetime
     *
     * @param createDatetime the value for diary_info.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_info.update_datatime
     *
     * @return the value of diary_info.update_datatime
     *
     * @mbggenerated
     */
    public Date getUpdateDatatime() {
        return updateDatatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_info.update_datatime
     *
     * @param updateDatatime the value for diary_info.update_datatime
     *
     * @mbggenerated
     */
    public void setUpdateDatatime(Date updateDatatime) {
        this.updateDatatime = updateDatatime;
    }
}