package com.inz.about.model;

import java.util.Date;

public class DiaryFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_file.maper_id
     *
     * @mbggenerated
     */
    private String maperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_file.diary_id
     *
     * @mbggenerated
     */
    private String diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_file.file_id
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_file.maper_order
     *
     * @mbggenerated
     */
    private String maperOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_file.maper_memo
     *
     * @mbggenerated
     */
    private String maperMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_file.enable
     *
     * @mbggenerated
     */
    private String enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_file.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_file.update_datetime
     *
     * @mbggenerated
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_file.maper_id
     *
     * @return the value of diary_file.maper_id
     *
     * @mbggenerated
     */
    public String getMaperId() {
        return maperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_file.maper_id
     *
     * @param maperId the value for diary_file.maper_id
     *
     * @mbggenerated
     */
    public void setMaperId(String maperId) {
        this.maperId = maperId == null ? null : maperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_file.diary_id
     *
     * @return the value of diary_file.diary_id
     *
     * @mbggenerated
     */
    public String getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_file.diary_id
     *
     * @param diaryId the value for diary_file.diary_id
     *
     * @mbggenerated
     */
    public void setDiaryId(String diaryId) {
        this.diaryId = diaryId == null ? null : diaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_file.file_id
     *
     * @return the value of diary_file.file_id
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_file.file_id
     *
     * @param fileId the value for diary_file.file_id
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_file.maper_order
     *
     * @return the value of diary_file.maper_order
     *
     * @mbggenerated
     */
    public String getMaperOrder() {
        return maperOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_file.maper_order
     *
     * @param maperOrder the value for diary_file.maper_order
     *
     * @mbggenerated
     */
    public void setMaperOrder(String maperOrder) {
        this.maperOrder = maperOrder == null ? null : maperOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_file.maper_memo
     *
     * @return the value of diary_file.maper_memo
     *
     * @mbggenerated
     */
    public String getMaperMemo() {
        return maperMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_file.maper_memo
     *
     * @param maperMemo the value for diary_file.maper_memo
     *
     * @mbggenerated
     */
    public void setMaperMemo(String maperMemo) {
        this.maperMemo = maperMemo == null ? null : maperMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_file.enable
     *
     * @return the value of diary_file.enable
     *
     * @mbggenerated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_file.enable
     *
     * @param enable the value for diary_file.enable
     *
     * @mbggenerated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_file.create_datetime
     *
     * @return the value of diary_file.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_file.create_datetime
     *
     * @param createDatetime the value for diary_file.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_file.update_datetime
     *
     * @return the value of diary_file.update_datetime
     *
     * @mbggenerated
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_file.update_datetime
     *
     * @param updateDatetime the value for diary_file.update_datetime
     *
     * @mbggenerated
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}