package com.inz.about.model;

public class DiaryPicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_picture.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_picture.diary_id
     *
     * @mbggenerated
     */
    private String diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_picture.picture_id
     *
     * @mbggenerated
     */
    private String pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_picture.picture_total
     *
     * @mbggenerated
     */
    private String pictureTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_picture.picture_order
     *
     * @mbggenerated
     */
    private String pictureOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_picture.picture_enable
     *
     * @mbggenerated
     */
    private String pictureEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_picture.id
     *
     * @return the value of diary_picture.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_picture.id
     *
     * @param id the value for diary_picture.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_picture.diary_id
     *
     * @return the value of diary_picture.diary_id
     *
     * @mbggenerated
     */
    public String getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_picture.diary_id
     *
     * @param diaryId the value for diary_picture.diary_id
     *
     * @mbggenerated
     */
    public void setDiaryId(String diaryId) {
        this.diaryId = diaryId == null ? null : diaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_picture.picture_id
     *
     * @return the value of diary_picture.picture_id
     *
     * @mbggenerated
     */
    public String getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_picture.picture_id
     *
     * @param pictureId the value for diary_picture.picture_id
     *
     * @mbggenerated
     */
    public void setPictureId(String pictureId) {
        this.pictureId = pictureId == null ? null : pictureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_picture.picture_total
     *
     * @return the value of diary_picture.picture_total
     *
     * @mbggenerated
     */
    public String getPictureTotal() {
        return pictureTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_picture.picture_total
     *
     * @param pictureTotal the value for diary_picture.picture_total
     *
     * @mbggenerated
     */
    public void setPictureTotal(String pictureTotal) {
        this.pictureTotal = pictureTotal == null ? null : pictureTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_picture.picture_order
     *
     * @return the value of diary_picture.picture_order
     *
     * @mbggenerated
     */
    public String getPictureOrder() {
        return pictureOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_picture.picture_order
     *
     * @param pictureOrder the value for diary_picture.picture_order
     *
     * @mbggenerated
     */
    public void setPictureOrder(String pictureOrder) {
        this.pictureOrder = pictureOrder == null ? null : pictureOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_picture.picture_enable
     *
     * @return the value of diary_picture.picture_enable
     *
     * @mbggenerated
     */
    public String getPictureEnable() {
        return pictureEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_picture.picture_enable
     *
     * @param pictureEnable the value for diary_picture.picture_enable
     *
     * @mbggenerated
     */
    public void setPictureEnable(String pictureEnable) {
        this.pictureEnable = pictureEnable == null ? null : pictureEnable.trim();
    }
}