package com.inz.about.model;

import java.util.Date;

public class PictureInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.picture_id
     *
     * @mbggenerated
     */
    private String pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.picture_path
     *
     * @mbggenerated
     */
    private String picturePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.picture_sys
     *
     * @mbggenerated
     */
    private String pictureSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.picture_url
     *
     * @mbggenerated
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.picture_size
     *
     * @mbggenerated
     */
    private Double pictureSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.picture_type
     *
     * @mbggenerated
     */
    private String pictureType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.picture_enable
     *
     * @mbggenerated
     */
    private String pictureEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.picture_id
     *
     * @return the value of picture_info.picture_id
     *
     * @mbggenerated
     */
    public String getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.picture_id
     *
     * @param pictureId the value for picture_info.picture_id
     *
     * @mbggenerated
     */
    public void setPictureId(String pictureId) {
        this.pictureId = pictureId == null ? null : pictureId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.picture_path
     *
     * @return the value of picture_info.picture_path
     *
     * @mbggenerated
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.picture_path
     *
     * @param picturePath the value for picture_info.picture_path
     *
     * @mbggenerated
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.picture_sys
     *
     * @return the value of picture_info.picture_sys
     *
     * @mbggenerated
     */
    public String getPictureSys() {
        return pictureSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.picture_sys
     *
     * @param pictureSys the value for picture_info.picture_sys
     *
     * @mbggenerated
     */
    public void setPictureSys(String pictureSys) {
        this.pictureSys = pictureSys == null ? null : pictureSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.picture_url
     *
     * @return the value of picture_info.picture_url
     *
     * @mbggenerated
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.picture_url
     *
     * @param pictureUrl the value for picture_info.picture_url
     *
     * @mbggenerated
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.picture_size
     *
     * @return the value of picture_info.picture_size
     *
     * @mbggenerated
     */
    public Double getPictureSize() {
        return pictureSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.picture_size
     *
     * @param pictureSize the value for picture_info.picture_size
     *
     * @mbggenerated
     */
    public void setPictureSize(Double pictureSize) {
        this.pictureSize = pictureSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.picture_type
     *
     * @return the value of picture_info.picture_type
     *
     * @mbggenerated
     */
    public String getPictureType() {
        return pictureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.picture_type
     *
     * @param pictureType the value for picture_info.picture_type
     *
     * @mbggenerated
     */
    public void setPictureType(String pictureType) {
        this.pictureType = pictureType == null ? null : pictureType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.picture_enable
     *
     * @return the value of picture_info.picture_enable
     *
     * @mbggenerated
     */
    public String getPictureEnable() {
        return pictureEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.picture_enable
     *
     * @param pictureEnable the value for picture_info.picture_enable
     *
     * @mbggenerated
     */
    public void setPictureEnable(String pictureEnable) {
        this.pictureEnable = pictureEnable == null ? null : pictureEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.create_datetime
     *
     * @return the value of picture_info.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.create_datetime
     *
     * @param createDatetime the value for picture_info.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_info.update_time
     *
     * @return the value of picture_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_info.update_time
     *
     * @param updateTime the value for picture_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}