package com.inz.about.model;

public class StaticZipCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_zipcode.zip_id
     *
     * @mbggenerated
     */
    private String zipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_zipcode.static_region_id
     *
     * @mbggenerated
     */
    private String staticRegionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_zipcode.zip_number
     *
     * @mbggenerated
     */
    private String zipNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_zipcode.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_zipcode.zip_id
     *
     * @return the value of static_zipcode.zip_id
     *
     * @mbggenerated
     */
    public String getZipId() {
        return zipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_zipcode.zip_id
     *
     * @param zipId the value for static_zipcode.zip_id
     *
     * @mbggenerated
     */
    public void setZipId(String zipId) {
        this.zipId = zipId == null ? null : zipId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_zipcode.static_region_id
     *
     * @return the value of static_zipcode.static_region_id
     *
     * @mbggenerated
     */
    public String getStaticRegionId() {
        return staticRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_zipcode.static_region_id
     *
     * @param staticRegionId the value for static_zipcode.static_region_id
     *
     * @mbggenerated
     */
    public void setStaticRegionId(String staticRegionId) {
        this.staticRegionId = staticRegionId == null ? null : staticRegionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_zipcode.zip_number
     *
     * @return the value of static_zipcode.zip_number
     *
     * @mbggenerated
     */
    public String getZipNumber() {
        return zipNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_zipcode.zip_number
     *
     * @param zipNumber the value for static_zipcode.zip_number
     *
     * @mbggenerated
     */
    public void setZipNumber(String zipNumber) {
        this.zipNumber = zipNumber == null ? null : zipNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_zipcode.code
     *
     * @return the value of static_zipcode.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_zipcode.code
     *
     * @param code the value for static_zipcode.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}