package com.inz.about.model;

public class StaticRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_region.static_region_id
     *
     * @mbggenerated
     */
    private String staticRegionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_region.static_region_name
     *
     * @mbggenerated
     */
    private String staticRegionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_region.static_city_id
     *
     * @mbggenerated
     */
    private String staticCityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_region.static_region_id
     *
     * @return the value of static_region.static_region_id
     *
     * @mbggenerated
     */
    public String getStaticRegionId() {
        return staticRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_region.static_region_id
     *
     * @param staticRegionId the value for static_region.static_region_id
     *
     * @mbggenerated
     */
    public void setStaticRegionId(String staticRegionId) {
        this.staticRegionId = staticRegionId == null ? null : staticRegionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_region.static_region_name
     *
     * @return the value of static_region.static_region_name
     *
     * @mbggenerated
     */
    public String getStaticRegionName() {
        return staticRegionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_region.static_region_name
     *
     * @param staticRegionName the value for static_region.static_region_name
     *
     * @mbggenerated
     */
    public void setStaticRegionName(String staticRegionName) {
        this.staticRegionName = staticRegionName == null ? null : staticRegionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_region.static_city_id
     *
     * @return the value of static_region.static_city_id
     *
     * @mbggenerated
     */
    public String getStaticCityId() {
        return staticCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_region.static_city_id
     *
     * @param staticCityId the value for static_region.static_city_id
     *
     * @mbggenerated
     */
    public void setStaticCityId(String staticCityId) {
        this.staticCityId = staticCityId == null ? null : staticCityId.trim();
    }
}