package com.inz.about.model;

public class StaticCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_city.static_city_id
     *
     * @mbggenerated
     */
    private String staticCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_city.static_city_name
     *
     * @mbggenerated
     */
    private String staticCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_city.static_province_id
     *
     * @mbggenerated
     */
    private String staticProvinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_city.first_letter
     *
     * @mbggenerated
     */
    private String firstLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_city.is_hot
     *
     * @mbggenerated
     */
    private String isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column static_city.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_city.static_city_id
     *
     * @return the value of static_city.static_city_id
     *
     * @mbggenerated
     */
    public String getStaticCityId() {
        return staticCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_city.static_city_id
     *
     * @param staticCityId the value for static_city.static_city_id
     *
     * @mbggenerated
     */
    public void setStaticCityId(String staticCityId) {
        this.staticCityId = staticCityId == null ? null : staticCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_city.static_city_name
     *
     * @return the value of static_city.static_city_name
     *
     * @mbggenerated
     */
    public String getStaticCityName() {
        return staticCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_city.static_city_name
     *
     * @param staticCityName the value for static_city.static_city_name
     *
     * @mbggenerated
     */
    public void setStaticCityName(String staticCityName) {
        this.staticCityName = staticCityName == null ? null : staticCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_city.static_province_id
     *
     * @return the value of static_city.static_province_id
     *
     * @mbggenerated
     */
    public String getStaticProvinceId() {
        return staticProvinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_city.static_province_id
     *
     * @param staticProvinceId the value for static_city.static_province_id
     *
     * @mbggenerated
     */
    public void setStaticProvinceId(String staticProvinceId) {
        this.staticProvinceId = staticProvinceId == null ? null : staticProvinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_city.first_letter
     *
     * @return the value of static_city.first_letter
     *
     * @mbggenerated
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_city.first_letter
     *
     * @param firstLetter the value for static_city.first_letter
     *
     * @mbggenerated
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter == null ? null : firstLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_city.is_hot
     *
     * @return the value of static_city.is_hot
     *
     * @mbggenerated
     */
    public String getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_city.is_hot
     *
     * @param isHot the value for static_city.is_hot
     *
     * @mbggenerated
     */
    public void setIsHot(String isHot) {
        this.isHot = isHot == null ? null : isHot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column static_city.state
     *
     * @return the value of static_city.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column static_city.state
     *
     * @param state the value for static_city.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}